name: kiarina-python

services:

  redis:
    container_name: kiarina-python-redis
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  falkordb:
    container_name: kiarina-python-falkordb
    image: falkordb/falkordb:latest
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
