name: Bug Report
description: Report a bug to help us improve
title: "[Bug] "
labels: ["bug", "triage"]
assignees:
  - kiarina

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Please note: This is a personal OSS project. While issues and PRs are welcome, 
        I don't actively seek contributions and work on this at my own pace.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - kiarina-utils-common
        - kiarina-utils-file
        - kiarina-llm
        - kiarina-lib-falkordb
        - kiarina-lib-redis
        - kiarina-lib-redisearch
        - Multiple packages
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment.
        You can get Python version with: `python --version`
        You can get package version with: `pip show <package-name>`
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.12.0]
        - Package version: [e.g., kiarina-utils-file==0.1.0]
        - Installation method: [e.g., pip, uv, poetry]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including logs, screenshots, etc.
