kiarina.lib.google.auth:
  service_account:
    type: service_account
    project_id: your-project-id
    service_account_email: your-service-account@your-project.iam.gserviceaccount.com
    service_account_file: ~/.gcp/service-account/your-project/your-service-account/key.json
kiarina.lib.google.cloud_storage:
  default:
    bucket_name: your-bucket-name
    blob_name_pattern: "my-service/{tenant_id}/users/{user_id}/files/{basename}"
