#!/usr/bin/env bash
#MISE description="Run format and lint for all packages"

set -euo pipefail

while IFS= read -r package; do
    mise run package:format "$package"
    mise run package:lint "$package"
done < <(mise run get-packages)
