#!/usr/bin/env bash
#MISE description="Run format, lint-fix, typecheck *"

set -euo pipefail

while IFS= read -r package; do
    mise run package:lint-fix "$package"
    mise run package:format "$package"
    mise run package:typecheck "$package"
done < <(mise run get-packages)
